steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "The short SHA is: $SHORT_SHA"'
  # ... rest of your steps ...

  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/backend:$SHORT_SHA', 
      '-f', 'backend/Dockerfile', 
      './backend'
    ]
  # Deploy the backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      "gcloud", "run", "deploy", "audio-backend",
      "--image", "us-central1-docker.pkg.dev/$PROJECT_ID/my-app/backend:$SHORT_SHA",
      "--platform", "managed",
      "--region", "us-central1",
      "--allow-unauthenticated"
    ]
  # Build the worker image (using WorkerDockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/worker:$SHORT_SHA', 
      '-f', 'backend/WorkerDockerfile', 
      './backend'
    ]
  # Deploy the worker service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      "gcloud", "run", "deploy", "audio-worker",
      "--image", "us-central1-docker.pkg.dev/$PROJECT_ID/my-app/worker:$SHORT_SHA",
      "--platform", "managed",
      "--region", "us-central1",
      "--no-allow-unauthenticated"
    ]
  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/frontend:$SHORT_SHA', 
      '-f', 'frontend/Dockerfile', 
      './frontend'
    ]
  # Deploy the frontend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      "gcloud", "run", "deploy", "audio-frontend",
      "--image", "us-central1-docker.pkg.dev/$PROJECT_ID/my-app/frontend:$SHORT_SHA",
      "--platform", "managed",
      "--region", "us-central1",
      "--allow-unauthenticated"
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/worker:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app/frontend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
